services:
  database:
  image: postgres:15:2
  restart: always
  ports:
    - '5432:5432'
  environment:
    -POSTGRES_USER: myuser
    -POSTGRES_PASSWORD: secretpassword
    -POSTGRES_DB: taskmanager